import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import {
  jobindsatsTitleLocales as locales,
  mergeDuplicateCsvRows,
  normalizeCsvRow,
  parseCsvRows,
  type JobindsatsTitleLocale as LocaleCode,
} from "./jobindsats-title-csv-utils";

function escapeForTsLiteral(value: string) {
  return value.replace(/[\u007f-\uffff]/g, (char) => {
    const code = char.charCodeAt(0).toString(16).padStart(4, "0");
    return `\\u${code}`;
  });
}

function toQuotedTsString(value: string) {
  return JSON.stringify(value).replace(/[\u007f-\uffff]/g, (char) => escapeForTsLiteral(char));
}

function buildMapBlock(
  name: string,
  entries: Array<[string, string]>,
  typed: "record" | "partial-record",
  typeName?: string,
) {
  const typeDeclaration =
    typed === "record"
      ? "Record<string, string>"
      : `Partial<Record<${typeName ?? "string"}, string>>`;

  const lines = entries.map(([key, value]) => `  ${toQuotedTsString(key)}: ${toQuotedTsString(value)},`);
  return [`const ${name} = {`, ...lines, `} satisfies ${typeDeclaration};`, ""].join("\n");
}

function main() {
  const csvPath = path.join(process.cwd(), "data", "jobindsats-titles.csv");
  const outputPath = path.join(process.cwd(), "lib", "i18n", "generated", "jobindsats-title-translations.ts");
  const rows = mergeDuplicateCsvRows(parseCsvRows(readFileSync(csvPath, "utf8")).map(normalizeCsvRow));

  const englishEntries = rows.map((row) => [row.da_key, row.en]) as Array<[string, string]>;
  const localeEntryMaps = Object.fromEntries(
    locales
      .filter((locale) => locale !== "en")
      .map((locale) => [
        locale,
        rows
          .filter((row) => row[locale].trim().length > 0)
          .map((row) => [row.da_key, row[locale]] as [string, string]),
      ]),
  ) as Record<Exclude<LocaleCode, "en">, Array<[string, string]>>;

  const content = [
    "// AUTO-GENERATED FROM data/jobindsats-titles.csv",
    "// DO NOT EDIT THIS FILE DIRECTLY.",
    "",
    buildMapBlock("enJobindsatsTitleTranslations", englishEntries, "record"),
    "export type JobindsatsTitleKey = keyof typeof enJobindsatsTitleTranslations;",
    "",
    ...Object.entries(localeEntryMaps).flatMap(([locale, entries]) => [
      buildMapBlock(`${locale}JobindsatsTitleTranslations`, entries, "partial-record", "JobindsatsTitleKey"),
    ]),
    "export {",
    "  enJobindsatsTitleTranslations,",
    "  ukJobindsatsTitleTranslations,",
    "  arJobindsatsTitleTranslations,",
    "  faJobindsatsTitleTranslations,",
    "  urJobindsatsTitleTranslations,",
    "  plJobindsatsTitleTranslations,",
    "  deJobindsatsTitleTranslations,",
    "};",
    "",
  ].join("\n");

  mkdirSync(path.dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content, "utf8");
  console.log(`Wrote generated Jobindsats translations to ${outputPath}`);
}

main();
